### ISSUE TITLE
No explanation of healing items like berries in inventory

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#101]
There's no proper explanation of items like berries in the inventory, especially how much HP they heal.
Ironically, the shop tooltip is much more informative on these items than the inventory itself.

Seems like the inventory tooltips need to become a little bit more informative.

I don't have a fleshed-out suggestion here, I'm just pointing out here some inconsistencies.

**Comment by Wuzzy2** [comment]
Likewise, the crafting table doesn't explain any of the items as well.

**Comment by MaxMraz** [comment]
The healing items are explained when you first pick them up, and I don't think it's worth rewriting the inventory system just to explain how many hearts each heals. There's only three to remember, I don't think the player's hand needs to be held _that_ much.

For the crafting table, I think the potions are all _fairly_ obvious by their name. Burlyblade makes your blade more burly- increases attack power, etc. Some of the feel of a game's world is communicated to the player by what things you _don't_ explain. If everything is fully explained and all results of their actions are shown to the player ahead of time, that creates a certain kind of feeling about the world. I want a kind of different feeling.

As far as the shops explaining it more, though, I figure that's because Tilia is talking to a person selling an item, so they'd explain what it is.

Anyway, I did add dialogs that pop up when you take a potion, making their effects more explicit in case you somehow have no idea if it's done anything.
