### ISSUE TITLE
Plot holes

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#114]
- Benjamin in the Yarrowmouth Distillery doesn't react at all after you killed Michael
- Juneberry Inn dude doesn't notice when you open the locked door

Tested in: 34a5e24

More plot holes might be posted later. :)

**Comment by Wuzzy2** [comment]
* Veilwood Village: When you enter the monster cave (for the apple quest), you get told this hole is dug out by monsters. But this doesn't make sense, you can clearly see wooden posts and a ladder already.
* If you blow up the wooden wall in the basement of Oakhaven Pub, the guy doesn't update its text
* Oakhaven bomb shop: When you talk to the bomb maker, he tells you they don't have any bombs, but you can see bombs standing on the shelves already
* After you found Hazel, the palace is raided by pirates and you have to fight your way through. The map on which the raid happens looks exactly like the birthday party courtyard map, just without the party. So it looks like the pirates have crashed the party. But if you mange to get out alive, then walk back into the palace, the dog birthday party is back up as if nothing happened! It seems this Hazel quest logically conflicts with the Dog Birthday quest; they don't really co-exist well together

For the last one: I suggest to replace the map in which the pirates raid you. Maybe instead of using the palace courtyard, come up with a different area of the palace that can't be seen anywhere else. Maybe make a fight sequence on some palace roofs or walls, or a completely different garden; just invent an area that can't be seen anywhere else.

**Comment by MaxMraz** [comment]
Adressed Juneberry inn and Oakhaven Saloon. Benjamin does react, he mentions that he's recently become the owner of the meadery and now will pay you more for his sidequest, because he has the power to set his own prices.

Veilwood is kinda an affordance that there's a ladder, the Bomb Shop guy is lying, so those won't be addressed.

The Palace Raid is admittedly a bit weird that nobody mentions that before the party started, there were a bunch of pirates. However, I don't think this is a big deal. Technically, none of the buildings in this game are as big on the outside as they are on the inside, but that's understood as a function of video games, and disbelief is suspended. I think the pirate raid is basically the same thing.

If i have extra time at some point, I might address this with NPCs talking about how a pirate raid ran through the party
