### ISSUE TITLE
NPC can traverse hero

### ISSUE THREAD

**Issue by Renkineko** [MaxMraz/oceans-heart#36]
When a NPC is walking, it goes thru the hero, giving a strange feeling (and blocking momentarily the hero). Don't know if normal and wanted or not :)

example: walking NPC in goatshed harbor

**Comment by MaxMraz** [comment]
Intended behavior. The other options are potentially trapping a player in a corner as they can't move past the NPC, or creating a much more complex AI-esque pathing system for NPCs. Especially since some of the moement types in Solarus seem a smidge broken, this is just so much simpler, even if it does feel a bit weird
