### ISSUE TITLE
Cannot hover burdock roots and similar items in inventory

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#95]
I cannot hover the burdock roots and similar collectibles in the inventory to learn what it is.

**Comment by MaxMraz** [comment]
Honestly, the names don't particularly matter.

Use cases for foraging and monster drops:
- Selling (Icon is shown in sell menu)
- Crafting (Icon is shown in crafting menu)

Since the icon is actually common in every situation you can use these items, I think saving space and making the code simpler by only showing the icon is efficient.
