### ISSUE TITLE
[suggestion/feedback] Dialog windows readability

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#98]
This is a suggestion or feedback.

I noticed while reading the dialog texts (when talking with people) I often didn't realize who was talking. I know it's written down, but it could be eye-friendlier. :-)

I suggest:

- Show a picture of the speaker
- Colorize the name of the speaker, which different colors for different speakers, to make it more distinguishable
- Maybe highlight important keywords in the text as well (if you don't do this already)

Another thing:
The dialog windows are inconsistent in whether a speaker name is even shown at all. Some windows have a name, sometimes they don't have one. Inconsistency is bad for readability IMO. I suggest if the speaker name is meant to be unknown, just show something generic, e.g. “man”, “woman”, “person”, etc.

**Comment by MaxMraz** [comment]
Something I've been meaning to do forever is to turn the dialog blue when Tilia is talking. Finally implemented this!

Trying to decide now if the entire dialog ought to be colored when Tilia is speaking, or just her name.


Also, the dialog isn't inconsistent, if their name is important, or if Tilia speaks back to them, there's no name. Otherwise, their name is shown. I suppose it's not uniform across all dialogs, but there are consistent rules.
